### ISSUE TITLE
JOSS Review: README.md

### ISSUE THREAD

**Issue by yxqd** [jarvist/PolaronMobility.jl#2]
@jarvist Please consider simplify the README.md. Some of the information there is now available at the documentation site https://jarvist.github.io/PolaronMobility.jl/ and looks duplicate. It would be nice that README.md is a succinct summary and defer more elaborate discussions to the documentation site. [This](https://github.com/ropensci/hydroscoper/blob/052a37e96255feef86c4ad1a38a6517db4d6e11e/README.md) might be a good example.

See also: #1, openjournals/joss-reviews#566

**Comment by jarvist** [comment]
Hopefully https://github.com/jarvist/PolaronMobility.jl/commit/f6c8a9b616abf4240bc9bdae84007c4b7639d23f#diff-04c6e90faac2675aa89e2176d2eec7d8 and https://github.com/jarvist/PolaronMobility.jl/commit/7d09de64704af5b0652b61a6adf6b0d0ecd83a75#diff-04c6e90faac2675aa89e2176d2eec7d8 achieve this. 
If that's sufficient, could you close the issue?
