### ISSUE TITLE
JOSS review: readme

### ISSUE THREAD

**Issue by lheagy** [jarvist/PolaronMobility.jl#3]
These are just a few minor suggestions accompanying the review, they don't need to hold up the publication. 
- it is common to put all of the badges at the top of the readme (where you have the build and coverage), I would suggest including the badge for the docs there as well. 
- do you have an example that runs on JuliaBox? https://www.juliabox.com/. I tried getting the package to build there, but the build failed. This might be a helpful way to get people up and running, but again, it is not required for the JOSS submission

**Comment by jarvist** [comment]
With commit fd3aa5f, both of these are done.
